[package]
name = "bevy_third_person_camera"
version = "0.1.11"
edition = "2021"
description = "A third person camera written for Bevy"
keywords = ["bevy", "camera", "orbit", "gamedev"]
categories = ["game-development"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/AndrewCS149/bevy_third_person_camera"
homepage = "https://github.com/AndrewCS149/bevy_third_person_camera"
readme = "README.md"
exclude = ["assets/*", "migrationGuides/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
avian3d = ["dep:avian3d"]

[dependencies]
bevy = { version = "0.14.1", default-features = false }
avian3d = { version = "0.1.2", default-features = false, optional = true }

[dev-dependencies]
bevy = "0.14.1"
